# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0008_categories_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.FloatField()),
                ('appointment_location', models.CharField(max_length=255)),
                ('teacher_attended', models.BooleanField(default=False)),
                ('student_attended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to='login_app.Users')),
                ('appointment_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_appointments', to='login_app.Users')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='login_app.SubCategories')),
            ],
        ),
    ]
