# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='appointment_student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='attending_appointments', to='login_app.Users'),
        ),
    ]
