# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 19:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 12, 56, 20, 419597)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='appointment_app.Reviews'),
        ),
    ]
