# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 20:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_auto_20190829_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='reviews',
        ),
        migrations.AddField(
            model_name='reviews',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='appointment_app.Appointments'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 13, 5, 26, 681811)),
        ),
    ]
