# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_auto_20190826_1431'),
        ('appointment_app', '0002_auto_20190826_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('content', models.TextField()),
                ('role', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_reviews', to='login_app.SubCategories')),
                ('review_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reviews', to='login_app.Users')),
                ('review_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to='login_app.Users')),
            ],
        ),
    ]
