# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 04:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_auto_20190828_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 21, 28, 12, 153517)),
        ),
    ]
