# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-29 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0002_auto_20190828_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 29, 8, 57, 46, 938752)),
        ),
    ]
