# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='student_attended',
            new_name='pending_credit',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='teacher_attended',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='login_app.SubCategories'),
        ),
    ]
