# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0003_auto_20190828_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 14, 54, 32, 56121)),
        ),
    ]
