# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0004_auto_20190826_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_time',
            new_name='appointment_end_time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_start_time',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
