# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0005_auto_20190826_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='appointment_end_time',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='appointment_start_time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='appointment_time',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
