# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0006_auto_20190826_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_time',
            new_name='time',
        ),
    ]
