# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 16:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0010_auto_20190826_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 9, 55, 23, 169066)),
        ),
    ]
