# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0015_auto_20190827_1435'),
        ('appointment_app', '0014_auto_20190827_1340'),
    ]

    operations = [
    ]
