# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0016_merge_20190827_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='category',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 27, 18, 39, 30, 127949)),
        ),
    ]
