# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0017_auto_20190827_1839'),
        ('appointment_app', '0019_auto_20190827_1728'),
    ]

    operations = [
    ]
