# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment_app', '0020_merge_20190828_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 28, 14, 19, 10, 771613)),
        ),
    ]
