# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='image_base',
        ),
    ]
