# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_remove_users_image_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image_base',
            field=models.TextField(default=None, null=True),
        ),
    ]
