# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_categories_subcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='credits',
            field=models.IntegerField(default=3),
        ),
    ]
