# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-26 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0009_users_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
