# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_auto_20190826_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='location',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='desc',
            field=models.TextField(default='', max_length=255),
        ),
    ]
