# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Image'),
        ),
    ]
