# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0014_users_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='image',
        ),
        migrations.AddField(
            model_name='users',
            name='image_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
