# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0015_auto_20190828_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='image_url',
        ),
        migrations.AddField(
            model_name='users',
            name='image',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login_app.Image'),
        ),
    ]
